# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import meterreader_pb2 as meterreader__pb2


class MeterReaderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadMeter = channel.unary_unary(
                '/MeterReader/ReadMeter',
                request_serializer=meterreader__pb2.MeterReaderRequest.SerializeToString,
                response_deserializer=meterreader__pb2.MeterReaderResponse.FromString,
                )


class MeterReaderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadMeter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeterReaderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadMeter': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadMeter,
                    request_deserializer=meterreader__pb2.MeterReaderRequest.FromString,
                    response_serializer=meterreader__pb2.MeterReaderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MeterReader', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MeterReader(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadMeter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MeterReader/ReadMeter',
            meterreader__pb2.MeterReaderRequest.SerializeToString,
            meterreader__pb2.MeterReaderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
